import os
import subprocess
import pytest
import sys
from pathlib import Path

def test_dvc_pipeline():
    """
    Test that the DVC pipeline is valid and can be reproduced.
    This verifies that 'dvc repro' runs the training script and tracks the output.
    """
    # Find the DVC executable path
    # In a venv, it should be in Scripts/dvc.exe on Windows
    python_path = Path(sys.executable)
    dvc_path = python_path.parent / "dvc"
    
    if sys.platform == "win32":
        dvc_path = python_path.parent / "dvc.exe"
        if not dvc_path.exists():
             # Fallback: try 'dvc' and hope it's in PATH, or check Scripts folder if python is not in Scripts
             # Sometimes python is in .venv/Scripts/python.exe, so dvc is in .venv/Scripts/dvc.exe
             # If python is in .venv/bin/python (linux), dvc is in .venv/bin/dvc
             pass
    
    dvc_cmd = str(dvc_path) if dvc_path.exists() else "dvc"

    # 1. Initialize DVC if not already done
    if not os.path.exists(".dvc"):
        try:
            # Use shell=True on Windows to find the command if it's a batch file or similar
            subprocess.run(f"{dvc_cmd} init --no-scm", shell=True, check=True, capture_output=True)
        except subprocess.CalledProcessError as e:
            pytest.fail(f"Failed to init dvc: {e}\nStderr: {e.stderr.decode()}")

    # 2. Check dvc.yaml existence
    assert os.path.exists("dvc.yaml"), "dvc.yaml is missing"

    # 3. Run dvc repro
    # Use shell=True for Windows compatibility when calling CLI tools
    result = subprocess.run(f"{dvc_cmd} repro", shell=True, capture_output=True, text=True)
    
    # 4. Assert success
    assert result.returncode == 0, f"DVC repro failed.\nStdout: {result.stdout}\nStderr: {result.stderr}"
    
    # 5. Verify output exists
    assert os.path.exists("artifacts/model.joblib"), "Model artifact not generated by dvc repro"
    assert os.path.exists("dvc.lock"), "dvc.lock not generated"
